version: "2.4"

services:
  # PostgreSQL
  aurad:
    container_name: aurad_erascope
    image: auranw/local-aurad:dev_v0.7.0-3
    ports:
      - "1317:1317"
      - "26656:26656"
      - "26657:26657"
      - "9090:9090"
    networks:
      - dev_network
    # depends_on:
    #   - psql

  psql:
    build: ./docker/psql/
    container_name: psql_erascope
    env_file: docker.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Redis
  redis:
    image: redis:latest
    container_name: redis_erascope
    ports:
      - "6379:6379"
    networks:
      - dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dev_network:

volumes:
  pgdata:
