version: '3.3'

services:
  aurad:
    container_name: aurad_erascope
    image: auranw/local-aurad:dev_v0.7.0-3
    ports:
      - '1317:1317'
      - '26656:26656'
      - '26657:26657'
      - '9090:9090'
    networks:
      - dev_network
    # depends_on:
    #   - psql

  psql:
    container_name: psql_erascope
    build: ./docker/psql/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_TEST: ${POSTGRES_DB_TEST}
    networks:
      - dev_network
  adminer:
    container_name: adminer
    image: adminer:4-standalone
    restart: always
    ports:
      - '8080:8080'
    networks:
      - dev_network

  redis:
    image: redis:latest
    container_name: redis_erascope
    ports:
      - '6379:6379'
    networks:
      - dev_network

  graphql-engine:
    image: hasura/graphql-engine:v2.12.1
    ports:
      - '8888:8080'
    depends_on:
      - 'psql'
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/hasura
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      DATABASE_URL_XSTAXY: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      DATABASE_URL_EVMOS_TESTNET: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      DATABASE_URL_TESTNET: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      DATABASE_URL_EUPHORIA: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      DATABASE_URL_SERENITY: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      DATABASE_URL_PACIFIC: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to run console offline (i.e load console assets from server instead of CDN)
      # HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  data:
