name: Dev Pre-release (semantic-release)

on:
  push:
    branches:
      - dev

jobs:
  dev-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semantic-release
        id: semantic
        uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              { "name": "main" },
              { "name": "dev", "prerelease": "dev" }
            ]
          additional-packages: |
            [
              "@semantic-release/changelog",
              "@semantic-release/git",
              "@semantic-release/exec"
            ]
          plugins: |
            [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "angular",
                  "releaseRules": [
                    { "type": "refactor", "release": "patch" }
                  ]
                }
              ],
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              "@semantic-release/git",
              "@semantic-release/exec"
            ]

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push dev Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana:dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana:dev-${{ github.sha }}
