name: Dev Pre-release (semantic-release)

on:
  push:
    branches:
      - dev

jobs:
  dev-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run semantic-release (action)
        id: semantic
        uses: codfish/semantic-release-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branches: |
            [
              "release",
              { "name": "main", "prerelease": "build-fix" },
              { "name": "dev", "prerelease": "dev" }
            ]
          plugins: |
            [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "angular",
                  "releaseRules": [
                    { "type": "refactor", "release": "patch" }
                  ]
                }
              ],
              [
                "@semantic-release/npm",
                { "npmPublish": false }
              ],
              "@semantic-release/release-notes-generator"
            ]
