name: Dev Pre-release (semantic-release)

on:
  push:
    branches: [main, 'release/**']

jobs:
  dev-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Corepack pnpm
        run: |
          corepack enable

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run semantic-release
        id: semantic
        uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [
              'release',
              { 
                name: 'main',
                prerelease: 'dev'
              }
            ]
          plugins: |
            [
              [
                "@semantic-release/commit-analyzer",
                {
                  "preset": "angular",
                  "releaseRules": [
                    {
                      "type": "refactor",
                      "release": "patch"
                    },
                    {
                      "type": "build",
                      "release": "patch"
                    }                    
                  ]
                }
              ],
              [
                "@semantic-release/npm",
                {
                  "npmPublish": false
                }
              ],
              "@semantic-release/release-notes-generator",
            ]

      - name: Set version for apps and packages
        if: steps.semantic.outputs.new-release-published == 'true'
        run: |
          pnpm -r --topological version "$RELEASE_VERSION"

      - name: Docker login
        uses: docker/login-action@v2
        if: steps.semantic.outputs.new-release-published == 'true'
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build & push dev Docker image
        uses: docker/build-push-action@v5
        if: steps.semantic.outputs.new-release-published == 'true'        
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana-indexer:dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana-indexer:v${{ steps.semantic.outputs.RELEASE_MAJOR }}-dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana-indexer:v${{ steps.semantic.outputs.RELEASE_MAJOR }}.${{ steps.semantic.outputs.RELEASE_MINOR }}-dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana-indexer:v${{ steps.semantic.outputs.RELEASE_MAJOR }}.${{ steps.semantic.outputs.RELEASE_MINOR }}.${{ steps.semantic.outputs.RELEASE_PATCH }}-dev
            ${{ secrets.DOCKER_HUB_USERNAME }}/verana-indexer:v${{ steps.semantic.outputs.RELEASE_VERSION }}-dev
