name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release PR
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: verana-indexer
          bump-minor-pre-major: true
          token: ${{ secrets.GITHUB_TOKEN }}
